apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
# Perform this vendor by running `make`, as this requires local patches for chaining to work with aws-vpc-cni
  - path: gitvendor
    contents:
    - path: .
      git:
        url: https://github.com/linkerd/linkerd2
        ref: edge-23.4.1
      includePaths:
        - charts/linkerd2-cni/**/*
        - charts/partials/**/*
        - cni-plugin/deployment/scripts/install-cni.sh
      legalPaths: []

# The linkerd2-cni is replaced with an edge chart directly vendored from git in 'gitvendor'.
#      - path: linkerd2-cni
#        helmChart:
#          name: linkerd2-cni
#          version: 2.10.2
#          repository:
#            name: linkerd
#            url: https://helm.linkerd.io/stable
